apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}
spec:
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - resource:
        name: memory
        target:
          averageUtilization: {{ .Values.autoscaling.maxPercentOfMemoryUsage }}
          type: Utilization
      type: Resource
    - resource:
        name: cpu
        target:
          averageUtilization: {{ .Values.autoscaling.maxPercentOfCPUUsage }}
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.name }}