apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app.kubernetes.io/name: {{.Values.name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Values.name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Values.name}}
    spec:
      serviceAccountName: {{.Values.name}}
      securityContext:
        {}
      containers:
        - name: {{.Values.name}}
          securityContext:
            {}
          image: "{{.Values.image.domain}}/{{.Values.image.repository}}:{{.Values.image.tag }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - name: http
              containerPort: {{.Values.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /probe/liveness
              port: {{.Values.port}}
            initialDelaySeconds: {{.Values.deployment.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.deployment.livenessProbe.periodSeconds}}
          env:
            - name: ENVIRONMENT
              value: {{.Values.environment}}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
