apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
      tier: frontend
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        tier: frontend
    spec:
      containers:
        - name: {{ .Values.name }}
          image: ghcr.io/akazakou/{{ .Values.name }}/{{ .Values.name }}:latest
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: {{ .Values.name }}-configuration-volume
              mountPath: /app/config/default.json
              subPath: default.json
              readOnly: true
      volumes:
        - name: {{ .Values.name }}-configuration-volume
          configMap:
            name: {{ .Values.name }}-configuration
      imagePullSecrets:
        - name: github-cred
