apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ .Values.name }}-letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: a.v.kazakou@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: "{{ .Values.name }}-letsencrypt"
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "{{ .Values.name }}-letsencrypt"
spec:
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: "{{ .Values.name }}-letsencrypt"
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.name }}
              servicePort: 3000