apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: {{ .Values.name }}
    tier: frontend
spec:
  type: "{{ .Values.serviceType }}"
  ports:
    - port: 3000
  selector:
    app: {{ .Values.name }}
    tier: frontend
