apiVersion: v1
kind: Secret
metadata:
  name: github-cred
type: kubernetes.io/dockercfg
data:
  .dockercfg: |
    "eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8vIjp7InVzZXJuYW1lIjoiYWthemFrb3UiLCJwYXNzd29yZCI6ImM4NmM4YzcyZTc1NzExOGQ0NjM5OTMzMjExZTU4Y2U1MDQwZWQ1NGMiLCJlbWFpbCI6ImEudi5rYXpha291QGdtYWlsLmNvbSIsImF1dGgiOiJZV3RoZW1GcmIzVTZZemcyWXpoak56SmxOelUzTVRFNFpEUTJNems1TXpNeU1URmxOVGhqWlRVd05EQmxaRFUwWXc9PSJ9fX0="
