apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
