# GitRepo resolve conflicts section
# @see https://fleet.rancher.io/bundle-diffs/#generating-diffs-for-modified-gitrepos
diff:
  comparePatches:
    - apiVersion: apps/v1
      kind: Deployment
      name: crayfish
      operations:
        - {"op": "remove", "path": "/spec/replicas"} # ignoring changed value for auto-scaled deployments