---
name: Build Docker Image
on: [push]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Build Image
        run: |
          npm run docker:build

      - name: Push Image
        run: |
          npm run docker:push
