---
name: Build Docker Image
on: [push]

jobs:
  build_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUBLISHING_GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/akazakou/crayfish/crayfish:latest
          file: deploy/docker/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # trigger deployment hook for fleet https://fleet.rancher.io/webhook/
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: 'json-extended'
          webhook_url: ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.DEPLOYMENT_WEBHOOK_SECRET }}