---
name: Build Docker Image
on: [push]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          echo "GIT_HASH=$(echo $(git rev-parse HEAD))" >> $GITHUB_ENV
          echo "GIT_REF=$(echo $(git branch | grep \\* | cut -d ' ' -f2))" >> $GITHUB_ENV
          echo "GIT_URL=$(echo $(git config --get remote.origin.url))" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Build Image
        run: npm run docker:build

      - name: Login to GitHub Package Registry
        run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.PUBLISHING_GITHUB_TOKEN }}

      - name: Push Image
        run: npm run docker:push

      # trigger deployment hook for fleet https://fleet.rancher.io/webhook/
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: 'json-extended'
          webhook_url: ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.DEPLOYMENT_WEBHOOK_SECRET }}